AWSTemplateFormatVersion: 2010-09-09
Description: ND9991 C3 L4
Resource:
  EC2Instance:
    Type: 'AWS:EC2::Instance'
    Proerties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-017fecd1353bcc96e'
      InstanceType: t3.micro
  InstanceSecurityGroup:
    Type: 'AWS:EC2::SecurityGroup'
    Proerties:
      GroupDesciption: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0